//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string About_Detail {
            get {
                return ResourceManager.GetString("About_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string About_Image {
            get {
                return ResourceManager.GetString("About_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả giới thiệu.
        /// </summary>
        public static string About_MetaDescriptions {
            get {
                return ResourceManager.GetString("About_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string About_MetaKeywords {
            get {
                return ResourceManager.GetString("About_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string About_MetaTitle {
            get {
                return ResourceManager.GetString("About_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên .
        /// </summary>
        public static string About_Name {
            get {
                return ResourceManager.GetString("About_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string About_Status {
            get {
                return ResourceManager.GetString("About_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản bắt buộc.
        /// </summary>
        public static string Accountnamerequired {
            get {
                return ResourceManager.GetString("Accountnamerequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tài khoản thành công.
        /// </summary>
        public static string Addaccountsuccessfully {
            get {
                return ResourceManager.GetString("Addaccountsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công.
        /// </summary>
        public static string Addfailed {
            get {
                return ResourceManager.GetString("Addfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tài khoản không thành công.
        /// </summary>
        public static string Addingaccountfailed {
            get {
                return ResourceManager.GetString("Addingaccountfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm menu thành công.
        /// </summary>
        public static string Addmenusuccessfully {
            get {
                return ResourceManager.GetString("Addmenusuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm không thành công.
        /// </summary>
        public static string Addproductfailed {
            get {
                return ResourceManager.GetString("Addproductfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm sản phẩm thành công.
        /// </summary>
        public static string Addproductsuccessfully {
            get {
                return ResourceManager.GetString("Addproductsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại sản phẩm không thành công.
        /// </summary>
        public static string Addproducttypefailed {
            get {
                return ResourceManager.GetString("Addproducttypefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm slide thành công.
        /// </summary>
        public static string AddSlidesuccessfully {
            get {
                return ResourceManager.GetString("AddSlidesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại tin tức thành công.
        /// </summary>
        public static string Addsuccessfulnewscategories {
            get {
                return ResourceManager.GetString("Addsuccessfulnewscategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm loại sản phẩm thành công.
        /// </summary>
        public static string Addsuccessfulproductcategories {
            get {
                return ResourceManager.GetString("Addsuccessfulproductcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Category_MetaDescriptions {
            get {
                return ResourceManager.GetString("Category_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string Category_MetaKeywords {
            get {
                return ResourceManager.GetString("Category_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Category_MetaTitle {
            get {
                return ResourceManager.GetString("Category_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục .
        /// </summary>
        public static string Category_ParentID {
            get {
                return ResourceManager.GetString("Category_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string Category_ShowOnHome {
            get {
                return ResourceManager.GetString("Category_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Category_Status {
            get {
                return ResourceManager.GetString("Category_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục.
        /// </summary>
        public static string Content_CategoryID {
            get {
                return ResourceManager.GetString("Content_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả tin tức.
        /// </summary>
        public static string Content_Description {
            get {
                return ResourceManager.GetString("Content_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Content_Detail {
            get {
                return ResourceManager.GetString("Content_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Content_Image {
            get {
                return ResourceManager.GetString("Content_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Content_MetaDescriptions {
            get {
                return ResourceManager.GetString("Content_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá tin tức.
        /// </summary>
        public static string Content_MetaKeywords {
            get {
                return ResourceManager.GetString("Content_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Content_MetaTitle {
            get {
                return ResourceManager.GetString("Content_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nội dung.
        /// </summary>
        public static string Content_Name {
            get {
                return ResourceManager.GetString("Content_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Content_Status {
            get {
                return ResourceManager.GetString("Content_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin nóng.
        /// </summary>
        public static string Content_TopHot {
            get {
                return ResourceManager.GetString("Content_TopHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem.
        /// </summary>
        public static string Content_ViewCount {
            get {
                return ResourceManager.GetString("Content_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hành.
        /// </summary>
        public static string Content_Warranty {
            get {
                return ResourceManager.GetString("Content_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá thành công.
        /// </summary>
        public static string Deletesuccessful {
            get {
                return ResourceManager.GetString("Deletesuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Menu_DisplayOrder {
            get {
                return ResourceManager.GetString("Menu_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        public static string Menu_Link {
            get {
                return ResourceManager.GetString("Menu_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Menu_Status {
            get {
                return ResourceManager.GetString("Menu_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục tiêu.
        /// </summary>
        public static string Menu_Target {
            get {
                return ResourceManager.GetString("Menu_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn bản.
        /// </summary>
        public static string Menu_Text {
            get {
                return ResourceManager.GetString("Menu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại.
        /// </summary>
        public static string Menu_TypeID {
            get {
                return ResourceManager.GetString("Menu_TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại danh mục.
        /// </summary>
        public static string MenuType_Name {
            get {
                return ResourceManager.GetString("MenuType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tin tức bắt buộc.
        /// </summary>
        public static string Nametypeofnewsrequired {
            get {
                return ResourceManager.GetString("Nametypeofnewsrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng.
        /// </summary>
        public static string Order_CustomerID {
            get {
                return ResourceManager.GetString("Order_CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Order_ShipAddress {
            get {
                return ResourceManager.GetString("Order_ShipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Order_ShipEmail {
            get {
                return ResourceManager.GetString("Order_ShipEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT đặt hàng.
        /// </summary>
        public static string Order_ShipMobile {
            get {
                return ResourceManager.GetString("Order_ShipMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt hàng.
        /// </summary>
        public static string Order_ShipName {
            get {
                return ResourceManager.GetString("Order_ShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Order_Status {
            get {
                return ResourceManager.GetString("Order_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu bắt buộc.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục.
        /// </summary>
        public static string Product_CategoryID {
            get {
                return ResourceManager.GetString("Product_CategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mã sản phẩm.
        /// </summary>
        public static string Product_Code {
            get {
                return ResourceManager.GetString("Product_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Product_Description {
            get {
                return ResourceManager.GetString("Product_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Product_Detail {
            get {
                return ResourceManager.GetString("Product_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Product_Image {
            get {
                return ResourceManager.GetString("Product_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        public static string Product_IncludedVAT {
            get {
                return ResourceManager.GetString("Product_IncludedVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Product_MetaDescriptions {
            get {
                return ResourceManager.GetString("Product_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string Product_MetaKeywords {
            get {
                return ResourceManager.GetString("Product_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string Product_MetaTitle {
            get {
                return ResourceManager.GetString("Product_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh liên quan.
        /// </summary>
        public static string Product_MoreImages {
            get {
                return ResourceManager.GetString("Product_MoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        public static string Product_Price {
            get {
                return ResourceManager.GetString("Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá khuyến mãi.
        /// </summary>
        public static string Product_PromotionPrice {
            get {
                return ResourceManager.GetString("Product_PromotionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        public static string Product_Quantity {
            get {
                return ResourceManager.GetString("Product_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Product_Status {
            get {
                return ResourceManager.GetString("Product_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm mới.
        /// </summary>
        public static string Product_TopHot {
            get {
                return ResourceManager.GetString("Product_TopHot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lượt xem.
        /// </summary>
        public static string Product_ViewCount {
            get {
                return ResourceManager.GetString("Product_ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảo hành.
        /// </summary>
        public static string Product_Warranty {
            get {
                return ResourceManager.GetString("Product_Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự .
        /// </summary>
        public static string ProductCategory_DisplayOrder {
            get {
                return ResourceManager.GetString("ProductCategory_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string ProductCategory_MetaDescriptions {
            get {
                return ResourceManager.GetString("ProductCategory_MetaDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá .
        /// </summary>
        public static string ProductCategory_MetaKeywords {
            get {
                return ResourceManager.GetString("ProductCategory_MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề .
        /// </summary>
        public static string ProductCategory_MetaTitle {
            get {
                return ResourceManager.GetString("ProductCategory_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục .
        /// </summary>
        public static string ProductCategory_Name {
            get {
                return ResourceManager.GetString("ProductCategory_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục cha.
        /// </summary>
        public static string ProductCategory_ParentID {
            get {
                return ResourceManager.GetString("ProductCategory_ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề seo.
        /// </summary>
        public static string ProductCategory_SeoTitle {
            get {
                return ResourceManager.GetString("ProductCategory_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string ProductCategory_ShowOnHome {
            get {
                return ResourceManager.GetString("ProductCategory_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string ProductCategory_Status {
            get {
                return ResourceManager.GetString("ProductCategory_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật sản phẩm thành công.
        /// </summary>
        public static string Productupdatesuccessful {
            get {
                return ResourceManager.GetString("Productupdatesuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên menu bắt buộc.
        /// </summary>
        public static string RequiredMenuname {
            get {
                return ResourceManager.GetString("RequiredMenuname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm bắt buộc.
        /// </summary>
        public static string Requiredproductname {
            get {
                return ResourceManager.GetString("Requiredproductname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên slide bắt buộc.
        /// </summary>
        public static string RequiredSlidename {
            get {
                return ResourceManager.GetString("RequiredSlidename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        public static string Slide_Description {
            get {
                return ResourceManager.GetString("Slide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Slide_DisplayOrder {
            get {
                return ResourceManager.GetString("Slide_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string Slide_Image {
            get {
                return ResourceManager.GetString("Slide_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên kết.
        /// </summary>
        public static string Slide_Link {
            get {
                return ResourceManager.GetString("Slide_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Slide_Status {
            get {
                return ResourceManager.GetString("Slide_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Tag_Name {
            get {
                return ResourceManager.GetString("Tag_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tài khoản thành công.
        /// </summary>
        public static string Updateaccountsuccessfully {
            get {
                return ResourceManager.GetString("Updateaccountsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật slide thành công.
        /// </summary>
        public static string Updatedslidessuccessfully {
            get {
                return ResourceManager.GetString("Updatedslidessuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string Updatefailed {
            get {
                return ResourceManager.GetString("Updatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật menu thành công.
        /// </summary>
        public static string Updatemenusuccessful {
            get {
                return ResourceManager.GetString("Updatemenusuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tin tức thành công.
        /// </summary>
        public static string Updatenewssuccessfully {
            get {
                return ResourceManager.GetString("Updatenewssuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại tin tức thành công.
        /// </summary>
        public static string Updatenewstypesuccessfully {
            get {
                return ResourceManager.GetString("Updatenewstypesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại sản phẩm thành công.
        /// </summary>
        public static string Updateproducttypesuccessfully {
            get {
                return ResourceManager.GetString("Updateproducttypesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string User_Address {
            get {
                return ResourceManager.GetString("User_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huyện.
        /// </summary>
        public static string User_DistrictID {
            get {
                return ResourceManager.GetString("User_DistrictID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhóm.
        /// </summary>
        public static string User_GroupID {
            get {
                return ResourceManager.GetString("User_GroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string User_Password {
            get {
                return ResourceManager.GetString("User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string User_Phone {
            get {
                return ResourceManager.GetString("User_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉnh.
        /// </summary>
        public static string User_ProvinceID {
            get {
                return ResourceManager.GetString("User_ProvinceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string User_Status {
            get {
                return ResourceManager.GetString("User_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập.
        /// </summary>
        public static string User_UserName {
            get {
                return ResourceManager.GetString("User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm.
        /// </summary>
        public static string UserGroup_Name {
            get {
                return ResourceManager.GetString("UserGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
